# Generated by Django 5.2 on 2025-04-07 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bgimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='id',
        ),
        migrations.AddField(
            model_name='locations',
            name='loc_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bgimages',
            name='image_path',
            field=models.FilePathField(match='.*\\.(jpg|png)$', path='S:\\5580 Data Mining\\AppBackend\\media\\bgimages', recursive=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='image_path',
            field=models.FilePathField(match='.*\\.(jpg|png)$', path='S:\\5580 Data Mining\\AppBackend\\media\\locations', recursive=True),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pricePerNight', models.IntegerField()),
                ('roomType', models.CharField(max_length=32)),
                ('image_path', models.FilePathField(match='.*\\.(jpg|png)$', path='S:\\5580 Data Mining\\AppBackend\\media\\hotels', recursive=True)),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.locations')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
