# Generated by Django 5.2 on 2025-04-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_locations_id_locations_loc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgimages',
            name='image_path',
            field=models.FilePathField(match='.*\\.(jpg|png)$', path='S:\\5580 Data Mining\\AppBackend\\media\\locations', recursive=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_path',
            field=models.FilePathField(match='.*\\.(jpg|png)$', path='S:\\5580 Data Mining\\AppBackend\\media\\locations', recursive=True),
        ),
    ]
