# Generated by Django 5.2 on 2025-04-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bgimages_image_path_alter_hotel_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgimages',
            name='image_path',
            field=models.FilePathField(match='.*\\.(jpg|png)$', path='S:\\5580 Data Mining\\AppBackend\\media\\bgimages', recursive=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_path',
            field=models.FilePathField(match='.*\\.(jpg|png)$', path='S:\\5580 Data Mining\\AppBackend\\media\\hotels', recursive=True),
        ),
    ]
