# Generated by Django 5.2 on 2025-04-07 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bgimages_image_path_alter_hotel_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='pricePerNight',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='roomType',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('pk', models.CompositePrimaryKey('hotel_id', 'room_number', blank=True, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('pricePerNight', models.IntegerField()),
                ('roomType', models.CharField(max_length=32)),
                ('availableFom', models.DateField()),
                ('availableTo', models.DateField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.hotel')),
            ],
        ),
    ]
