# Generated by Django 5.2 on 2025-04-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_hotel_pricepernight_remove_hotel_roomtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='availableFom',
            new_name='availableFrom',
        ),
    ]
