# Generated by Django 5.2 on 2025-04-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_apitoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pk',
            field=models.CompositePrimaryKey('hotel_id', 'room_number', 'availableFrom', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
