# Generated by Django 5.2 on 2025-04-12 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_room_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('bookedFrom', models.DateField()),
                ('bookedTo', models.DateField()),
                ('bookedBy', models.TextField()),
                ('bookedByEmail', models.TextField()),
                ('paymentAmt', models.IntegerField()),
                ('guestCount', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.hotel')),
            ],
        ),
    ]
