# Generated by Django 5.2 on 2025-04-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_booking_id_booking_booking_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel_id', 'room_number', 'availableFrom'), name='unique_room_instance'),
        ),
    ]
